import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm"

[window]
opacity = 0.5

[font]
size = 12

[font.normal]
family = "Iosevka"
style = "Regular"

[font.bold]
family = "Iosevka"
style = "Bold"

[font.italic]
family = "Iosevka"
style = "Italic"
